### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by OsirisRoman** [danestves/strapi-plugin-colorpicker#5] opened 2021-06-25 17:00 UTC
With Strapi 3.6.5
`
Unexpected token # in JSON at position 0
SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at w (http://localhost:1337/admin/main.c4ffbc43.chunk.js:1:6312428)
    at Ka (http://localhost:1337/admin/main.c4ffbc43.chunk.js:1:4288785)
    at Ii (http://localhost:1337/admin/main.c4ffbc43.chunk.js:1:4297689)
    at gl (http://localhost:1337/admin/main.c4ffbc43.chunk.js:1:4336427)
    at cs (http://localhost:1337/admin/main.c4ffbc43.chunk.js:1:4327724)
    at ls (http://localhost:1337/admin/main.c4ffbc43.chunk.js:1:4327649)
    at Xl (http://localhost:1337/admin/main.c4ffbc43.chunk.js:1:4324658)
    at http://localhost:1337/admin/main.c4ffbc43.chunk.js:1:4276043
    at t.unstable_runWithPriority (http://localhost:1337/admin/main.c4ffbc43.chunk.js:1:4351623)
`

**Comment by danestves** [comment] 2021-06-25 19:20
Hey @OsirisRoman this plugin doesn't support Strapi 3.6 yet

**Comment by danestves** [comment] 2021-06-25 19:20
I'm going to close this issue due to a duplicate of https://github.com/danestves/strapi-plugin-colorpicker/issues/4

**Closed as completed by danestves** 2021-06-25 19:20 UTC
